<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>GET</name>
   <tag></tag>
   <elementGuidId>a4cc2f51-07eb-469f-8583-ac5f2395353a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>true</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <katalonVersion>10.1.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path>/api/v1/CoverPhotos/books/covers/{idBook}</path>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>//api/v1/CoverPhotos/books/covers/${idBook}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>null</defaultValue>
      <description>&lt;integer> {Required} null</description>
      <id>3011cbb8-d285-4dc2-9489-5c4af4ec6c5b</id>
      <masked>false</masked>
      <name>idBook</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
